### ISSUE TITLE
EventTrigger on event that fires before Loaded event does not work

### ISSUE THREAD

**Issue by tibel** [jlaanstra/Windows.UI.Interactivity#10]
I tried to attach a event trigger to the Opend event of the AppBar but the command was never called. On buttons inside the AppBar it is working (see issue #9).

``` xml
<Page.BottomAppBar>
  <AppBar VerticalAlignment="Bottom" x:Name="TestAppBar" IsSticky="True">
  <i:Interaction.Triggers>
  <i:EventTrigger EventName="Opened">
  <i:InvokeCommandAction Command="{Binding AppBarOpenedCommand}" />
  </i:EventTrigger>
  </i:Interaction.Triggers>
  <Grid>
  </Grid>
  </AppBar>
</Page.BottomAppBar>
```

**Comment by jmclain** [comment]
Problem seems to be that the "Opened" event on an element has been usurped to register the elements triggers but none of the triggers are check to see if they are the "Opened" event.

Should be able to check for "Opened" and then manually fire the event???

joe mclain

**Comment by jlaanstra** [comment]
Just wanted to let you know that I will look into this soon.

**Comment by jlaanstra** [comment]
Opened is fired before Loaded when the triggers and behaviors are attached, so there is currently no easy way to fix this. I will give it some more thought.

**Comment by kevinkuebler** [comment]
The same bug exists with the Closed event. Is it a similar issue to the Loaded event?

**Comment by xperiandri** [comment]
Do you remember that Blend creates collection of triggers on root element
Did you try to create it that way?
