### ISSUE TITLE
Problem with non routed events

### ISSUE THREAD

**Issue by nigel-sampson** [jlaanstra/Windows.UI.Interactivity#11]
It appears that some events on the controls in Windows.UI.Xaml.Controls have event args that don't inherit from RoutedEventArgs. The one that brought this to my attention was Windows.UI.Xaml.Controls.DragItemsStartingEventArgs which inherits from Object directly. 

This means that EventTrigger will not work on these events.

**Comment by tibel** [comment]
I think the same is with Control.IsEnabledChanged event, as DependencyPropertyChangedEventArgs inherits from Object directly. Maybe this is easier to test than drag&drop.

**Comment by jlaanstra** [comment]
This should fixed in the most recent release. Let me know if you have any other problems!

**Comment by NuFX** [comment]
Hey, im trying to get this workin to no avail. Im having a Gridview where i want to catch the DragItemsStarting event. I have already checked that the event gets fired and i can successfully wire up other events like ItemClick, but with the DragItemsStarting event there isnt invoked anything. Would be nice if u can provide a workin sample for this.
Btw. i tried the nuget package and the source.

**Comment by xperiandri** [comment]
Try to debug what is going on inside the Trigger
Or upload a sample solution so it can be looked at the problem

**Comment by NuFX** [comment]
Ok, i have modified the sample to show the problem. Just start the app and start dragging around the tiles.
Hint: Nothing happens, beside the rearranging ;)
Relevant code is in the GroupedItemsPage.
http://dl.dropbox.com/u/7811744/Windows.UI.Interactivity-master.zip

**Comment by NuFX** [comment]
Ok, i think i found the bug, dont know how to fix it though.
In EventTriggerBase it checks if the event is valid in IsValidEvent(EventInfo eventInfo).
Inside this method it returns false in the case of the DragItemsStarting event because DragItemsStartingEventArgs are not assignable to RoutedEventArgs.

Code:
return typeof(RoutedEventArgs).GetTypeInfo().IsAssignableFrom(parameters[1].ParameterType.GetTypeInfo());

Any tips how to fix that properly ?

**Comment by xperiandri** [comment]
Without rewriting Windows.UI.Interactivity, you can copy EventTrigger code, modify it the way you need and rename as you want.
However it may be reasonable to modify Windows.UI.Interactivity. Let's wait for jlaastra opinion.

**Comment by NuFX** [comment]
Yeah, i got it workin on my side for the Drag event. 
Would be nice if this could be fixed for all possible EventArgs that can occur.
Wondering if he somehow forgot to pull the fix into the source, since he already said that it is fixed.
Anyways thx for your support.

**Comment by nigel-sampson** [comment]
Yeah, looks like this isn't resolved, I'm still seeing problems with EventTrigger and non RoutedEvents.

**Comment by jlaanstra** [comment]
I will look into this when I get home today. Stay tuned.

**Comment by NuFX** [comment]
Yeah, workin now. Looks like an easy fix. I thought i would have to cast the arguments in the command if the code would be changed like this.
Thx.
