### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component

### ISSUE THREAD

**Issue by jmclain** [jlaanstra/Windows.UI.Interactivity#13]
```
Error HRESULT E_FAIL has been returned from a call to a COM component.
System.Runtime.InteropServices.COMException
   at Windows.UI.Xaml.FrameworkElement.get_DataContext()
   at Windows.UI.Interactivity.AttachableCollection`1.AssociatedObjectUnloaded(FrameworkElement elem)
   at Windows.UI.Interactivity.WeakLifetimeObserver.observedObject_Unloaded(Object sender, RoutedEventArgs e)
```

this is occurring in

```
        public void AssociatedObjectUnloaded(FrameworkElement elem)
        {
            Debug.WriteLine("{0} {2} unloaded from {1}", this.GetType(), (this.AssociatedObject != null) ? this.AssociatedObject.DataContext : null, this.GetHashCode());
            this.Detach();
        }
```

occasionally when Debug.WriteLine() is executed.

I don't believe this is an error in the functionality of WUI but is the result the attempt to access AssociatedObject.DataContext when the AssociatedObject is still live but the DataContext has gone away.

In any case, commenting out the Debug.WriteLiine() or modifying it to not reference DataContext fixes the issue.

Thanks for all the work

joe mclain

**Comment by jmclain** [comment]
I've confirmed that the Debug.WriteLine() is attempting to access a DataContext that was set to a ViewModel that has been garbage collected. My guess is that this is a WinRT bug since (I would think) a call to Windows.UI.Xaml.FrameworkElement.get_DataContext() should return either null or a valid object, not throw an exception.

In any case, I've wrapped the Debug.WriteLine() in a try/catch and wrapped the try/catch with a #if DEBUG.

```
#if DEBUG
                                try {
                                    Debug.WriteLine( "{0} {2} unloaded from {1}", this.GetType(), (this.AssociatedObject != null) ? this.AssociatedObject.DataContext : null, this.GetHashCode() );
                                }
                                catch {
                                    Debug.WriteLine( "{0} {1} unloaded, exception thrown when at attempt was made to access 'this.AssociatedObject.DataContext'", this.GetType(), this.GetHashCode() );
                                }
#endif
```

Thanks.

**Comment by jlaanstra** [comment]
Commented them out.
