### ISSUE TITLE
dll is not signed / strong name

### ISSUE THREAD

**Issue by Rickrat** [jlaanstra/Windows.UI.Interactivity#15]
Please sign the executable so it works with strong name executables.

**Comment by tibel** [comment]
Yes, please add strong name.

**Comment by tibel** [comment]
Just found these links:
- http://coderjournal.com/2012/04/json-net-strong-naming-and-nuget-woes/
- http://blog.devlex.net/post/2011/02/20/NuGet-updating-binding-redirects.aspx

Seems that strong naming may result in versioning problems...

**Comment by Rickrat** [comment]
Yeah, it depends on what you are trying to do.

**Comment by xperiandri** [comment]
What is the purpose of strong name in case of this package?

**Comment by jlaanstra** [comment]
Strong naming is useful if you have packages with strong naming that depend on it. Since not strong named packages have no problems with strong named assemblies there is no reason to not strong name it. 
The AssemblyVersion will not be updated for bug fixes to not cause any versioning trouble.
