### ISSUE TITLE
The purpose of IntractivityBase.OnDataContextChanged()

### ISSUE THREAD

**Issue by xperiandri** [jlaanstra/Windows.UI.Interactivity#16]
I'm porting Microsoft.Expression.Interations
So I'm interested in purpose of method "protected virtual void OnDataContextChanged(object oldValue, object newValue)" inside InteractivityBase class and corresponding dependency on FrameworkElement and not on DependencyObject like it was in source library form Silverlight or WPF.

**Comment by jlaanstra** [comment]
Hello xperiandri,

In WinRT the DataContext of an attached property is not set to the datacontext of the element we are attaching to. So we need to do some trickt to get the datacontext from the element. That is the reason we have an OnDataContextChanged method together with a few others.

Also in WinRT bindings do not seem to work with dependencyobjects but only with frameworkelements, at least not in the release preview. Which is why we depen on FrameworkElement.

**Comment by xperiandri** [comment]
But in case of DependencyObject there is no DataContext at all, isn't it?

**Comment by xperiandri** [comment]
What if FrameworkElement to which trigger or behavior is attached does not have DataContext set at all?
In this case execution stops on:

protected async Task<object> ConfigureDataContextAsync()
{
    return await tcs.Task;
}

And nothing happend

**Comment by jlaanstra** [comment]
You are right DependencyObject does not have a DataContext.

**Comment by xperiandri** [comment]
So I'm wondering why someone would need to have DataContext on Behavior or Trigger.
What is the purpose of this?
What is the scenario of its usage?

**Comment by jlaanstra** [comment]
I suppose you are familiar with the Data Binding in WinRT and also Silverlight and WPF? These bindings are performed on the DataContext, so if you do not have a DataContext, your bindings won't work.

**Comment by xperiandri** [comment]
In Silverlight and WPF - yes, in WinRT - not sure

My logic is:
In WPF and Silverlight behaviors and trigger derive from DependencyObject.
If you change this hierarchy than there might be a reason.
I've successfully ported Microsoft.Expression.Interactions to WinRT (I think so :)) and also my OrientationTrigger and OrientationToStateAction
Now I try to test it
I've attached them to page and nothing happened
I started to debug and what I've found is that when no DataContext is set then InteractivityBase just does not work!

**Comment by jlaanstra** [comment]
Can you share a sample with me so I can take a look?

**Comment by xperiandri** [comment]
Sorry, I was working with not latest version.
Can't figure out how to get latest.
My latest changes is on my fork

**Comment by xperiandri** [comment]
I'll make it tomorrow

**Comment by xperiandri** [comment]
I've committed to my fork
Could you have a look? It almost work.
I can't make bindings working. What did I miss?

**Comment by jlaanstra** [comment]
Can you detail what is not working, what should happen and were I can find the sample?

**Comment by xperiandri** [comment]
Are you able to download my fork?
There is App2 application where I try to test GoToStateAction and DataStateBehavior

**Comment by jlaanstra** [comment]
YOur binding is not working because of an elementname binding inside the behavior. For some reason this does not work. This is a WinRT issue and I can't fix that.
