### ISSUE TITLE
if DataContext is not set for FrameworkElement to which trigger or behavior is attached the attachment does not happen

### ISSUE THREAD

**Issue by xperiandri** [jlaanstra/Windows.UI.Interactivity#17]
What if FrameworkElement to which trigger or behavior is attached does not have DataContext set at all?
In this case execution stops on:

protected async Task ConfigureDataContextAsync()
{
    return await tcs.Task;
}

**Comment by jlaanstra** [comment]
The code your referencing is no longer in the source of Windows.UI.Interactivity. As far as I know the issue you are describing currently does not occur in the library.
