### ISSUE TITLE
SizeChangedEventHandler not firing

### ISSUE THREAD

**Issue by ghost** [jlaanstra/Windows.UI.Interactivity#18]
Hello!

To reproduce, run this simple example:
http://www.wiredprairie.us/blog/index.php/archives/847 

in a Windows Phone 7.5/8 app and then in a Window Store app and you will see a break point in the AttachedObjectSizeChanged() method is reached in the first app but not the second.

Thanks.

**Comment by jlaanstra** [comment]
The following minimal example works as expected for me:

class SizeChangedBehavior : Behavior<FrameworkElement>
    {
        protected override void OnAttached()
        {
            base.OnAttached();

```
        this.AssociatedObject.SizeChanged += AssociatedObject_SizeChanged;
    }

    protected override void OnDetaching()
    {
        base.OnDetaching();

        this.AssociatedObject.SizeChanged -= AssociatedObject_SizeChanged;
    }

    void AssociatedObject_SizeChanged(object sender, SizeChangedEventArgs e)
    {
        Debug.WriteLine("!!");
    }
}
```

Also the code you are referencing contains other flaws such as detaching a new event handler which can never be attached.

Regards,
