### ISSUE TITLE
Please add [assembly: CLSCompliant(true)]

### ISSUE THREAD

**Issue by tibel** [jlaanstra/Windows.UI.Interactivity#19]
This would make it more compatible to System.Windows.Interactivity.

**Comment by jlaanstra** [comment]
Marking Windows.UI.Interactivity as CLS compliant would inidicate something that is not true. If I add the attribute all kinds of warnings appear indicating that types used in WUI are not CLSCompliant, so I guess WUI also shouldn't be.

**Comment by tibel** [comment]
Oh, I did miss that. Thanks.
