### ISSUE TITLE
GoToStateAction?

### ISSUE THREAD

**Issue by bryanbcook** [jlaanstra/Windows.UI.Interactivity#21]
Noticed that there isn't a GoToStateAction, any reason why this wasn't ported?

**Comment by jlaanstra** [comment]
I ported only the System.Windows.Interactivity assembly, which does not contain the GoToStateAction.

**Comment by xperiandri** [comment]
Use port of Microsoft.Expression.Interactions from my branch

**Comment by bryanbcook** [comment]
@xperiandri why not issue a pull request and integrate it into the mainline? this is extremely useful stuff.

**Comment by xperiandri** [comment]
Thanks.
I will try it soon.
I have been testing it. There was an issue with binding to enum property. And I didn't tested storyboard behaviors
Test my port, please, for a while. And if you will have no issues I will pull it.
By the way, I also have OrientationAction and OrientatinTrigger to go to state depending on orientation.

**Comment by xperiandri** [comment]
And the main question: Jlaanstra, Will you add Microsoft.Expression.Interations to your NuGet?

**Comment by jlaanstra** [comment]
I think it is best to keep the two libraries separate, since Microsoft.Expression.Interactions is not a required part for using my library. At this time I don't see the added value of integrating it and I won't force an unnecessary dependency for users who do not use it.

**Comment by bryanbcook** [comment]
I can appreciate that decision. Though I'd like to add the following
suggestions:
1. The nuget package for windows.ui.interactivity doesn't work for Window
   RT app store projects. I can open a separate issue if needed but the
   package doesn't work with NuGet >2.1 -- it claims the package doesn't
   support the targeted framework.
2. Because of the packaging dependency between Windows.UI.Interactivity and
   the port of Microsoft.Expression.Interactions, @xperiandri should consider
   releasing a separate package that depends on the initial
   Windows.UI.Interactivity package.

On Mon, Jan 14, 2013 at 8:48 AM, Johan Laanstra notifications@github.comwrote:

> I think it is best to keep the two libraries separate, since
> Microsoft.Expression.Interactions is not a required part for using my
> library. At this time I don't see the added value of integrating it and I
> won't force an unnecessary dependency for users who do not use it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jlaanstra/Windows.UI.Interactivity/issues/21#issuecomment-12218834.

## 

regards,

Bryan Cook
bryanbcook@gmail.com
(416) 844-6178

**Comment by xperiandri** [comment]
OK.
I'll try to make it available as NuGet this month.
I have never created any NuGet package yet...
