### ISSUE TITLE
Please rename folder lib\win to lib\win8 in nuget package

### ISSUE THREAD

**Issue by tibel** [jlaanstra/Windows.UI.Interactivity#23]
Some tools seem to have problem with resolving 'win' to 'Windows 8.0' (e.g. NuGet Package Explorer win8 metro app).

**Comment by jlaanstra** [comment]
That folder is auto-generated by NuGet.exe pack during the creation of the package. I don't see any strange behavior in the Nuget Package Explorer metro app and according to the docs over [here](http://docs.nuget.org/docs/release-notes/nuget-2.1) win is valid. What problem do you have?

**Comment by tibel** [comment]
On [NuGet.org](https://nuget.org/packages/Caliburn.Micro) it looks good, but this i get when viewing in package explorer:
![caliburn micro_dependencies](https://f.cloud.github.com/assets/387395/81246/26d41a1c-630a-11e2-87b7-ac6f23b77d52.png)

**Comment by jlaanstra** [comment]
That's definitely a bug in the metro package explorer, but I will change it anyway with a manual nuspec file since the .pri files are also not automatically included.

**Comment by tibel** [comment]
Thanks.

I will create an issue in https://npe.codeplex.com for it.
