### ISSUE TITLE
NuGet package target

### ISSUE THREAD

**Issue by xperiandri** [jlaanstra/Windows.UI.Interactivity#25]
Maybe it is better to change NuGet target from win(windows,Version=8.0) to netcore45(.NETCore=v4.5)
As I understand win(windows,Version=8.0) is for libraries that can target Windows Store app in any language and runtime (C++, .NET, HTML/JScript), so dll have to be Runtime Component
And netcore45(.NETCore=v4.5) is just for .NET Windows Store apps.

What do you know about this difference?

**Comment by jlaanstra** [comment]
As far as I know there is no difference.
See also the framework targeting examples. http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Grouping_Assemblies_by_Framework_Version
