### ISSUE TITLE
Behavior lost after recycling

### ISSUE THREAD

**Issue by TheFabFab** [jlaanstra/Windows.UI.Interactivity#3]
Hi, and first of all thanks for your work.

I noticed that there's an issue if the behavior is set anywhere inside a ListViewItem or similar and it happens because Load and Unload are called multiple times on these - they are removed from the visual tree and then reinserted as the containers get recycled.

**Comment by jlaanstra** [comment]
This is a known problem with the current code. Unfortunately it is difficult to fix. We need to handle the Unloaded event on the attachedobject to detach the behavior because we leak memory otherwise.  Better would be to handle the Load and Unload events on the behavior itself, but they are not called for some reason.

You can work around this issue by setting the virtualizationmode on the virtualizing panel to standard instead of recycling.

**Comment by TheFabFab** [comment]
I see what you mean... the fact that the references go through native code (the attached property value in this case), makes life so much more complicated in WinRT.

Let's bramestorm a bit :)

You have these links:
1.) Asssociated object -> Behavior (attached property value)
2.) and 3.) Associated object -> Behavior (Loaded and Unloaded event subscription)
4.) Behavior -> Associated object (AssociatedObject property)

In pure .NET they would all go away together, without the need to break any links

In WinRT, link #1 goes through native code which makes the garbage collector unaware of the circular reference.

So what if on Unload you broke link #1 and kept link 2-4? Wouldn't that work?

You still might want to fire OnAttached and OnDetached on Loaded and Unloaded to allow the behavior to clean up...

I've been wrecking my brains for the last few days with WinRT leaks (some but not all coming from Windows.UI.Interactivity) and I'm determined to get to the bottom of the issue. :o) 

I'll try this later this week and get back to you.

**Comment by TheFabFab** [comment]
Ok, I gave it a go, here's the prototype: http://sdrv.ms/PqY1yY

I added a weak listener to FrameworkElement's lifetime events and if 'Loaded' is fired a second time, it will re-attach the behavior. The finalizer in my test behavior is called nicely, but obviously a bit more testing will be required. I'm going to include it into my project and see how I get on.

**Comment by jlaanstra** [comment]
How is your solution going at your side? I looked into it and it seems this would work if the GridViewItem fired its Loaded and Unloaded events correctly, which it doesn't, so for now I guess the only possibility is setting VirtualizationMode to Standard. Any issues on your side?

**Comment by TheFabFab** [comment]
I am seeing issues in Behavior.cs#54: await this.ConfigureDataContextAsync();

The data context seems to never change and OnAttached is never called in the next line.

**Comment by TheFabFab** [comment]
Posted too fast... lol

Adding a call to base from Behavior.Attach and .Detach seems to work... will test it a bit more and check for leaks.
