### ISSUE TITLE
AssociatedObject never assigned for Actions

### ISSUE THREAD

**Issue by jmclain** [jlaanstra/Windows.UI.Interactivity#6]
Hello jlaanstra,

You fixed "Exception in AttachableCollection<T>.AssociatedObject_Unloaded"; however it broke Caliburn - at least it broke my app. Pardon me if this does not make complete sense but I'm not fully understanding what W.U.I is doing, and I'm trying to keep what I did discover in my head long enough to describe it.

In AttachableCollection<T>, Attach() delays assigning AssociatedObject until a WeakLifetimeObserver instance calls AssociatedObjectLoaded() after the FrameworkElement (associated object) Loaded event is raised. AssociatedObject gets assigned; then AssociatedObjectLoaded() calls OnAttached().

  ->  this.OnAttached();

TriggerCollection.OnAttached() calls TriggerBase.Attach(AssociatedObject) for each item in the collection which in turn adds frameworkElement (the associated object) the the Actions collection. AttachableCollection<T>'s Attach() method is called, a WeakLifetimeObserver instance is generated so that the AssociateObject can be assigned when the framework element loads. 

The problem is that "Load" has already fired on the element; it is the Load event that has caused OnAttached() to be called. Anyway, the AssociatedObject is never initialized for the entries in the Action collection.

Hope you have a chanced to look at this. I currently have no workaround, still looking.

thanks

**Comment by jlaanstra** [comment]
Sorry I didn't test this. I fixed it in 0eb4ccade646c8764929ce62bcddd0819bed66ed.
