### ISSUE TITLE
AttachableCollection.AssociatedObject not being set when element is reloaded

### ISSUE THREAD

**Issue by jmclain** [jlaanstra/Windows.UI.Interactivity#7]
Hello jlaanstra,

Thanks for your efforts with W.U.I. Unfortunately I have found an additional issue with AttachableCollection and the setting of AssociatedObject.

TriggerBase.Detach() calls AttachableCollection.Detach() directly - there is no weak reference involved here. Because of this direct call to Detach() "isLoaded" is never set to false and the next time AttachableCollection.AssociatedObjectLoaded() is called AssociatedObject is not reinitialized - as you can imagine this causes all kinds of havoc!

I expect this behavior does not normally surface, but in the case of AppBars it does because the elements in an AppBar are loaded, unloaded and then loaded again as the Popup is shown, hidden and shown. The easy fix appears to be moving the assignment of "isLoaded" into AttachableCollection.Detach().

Thanks for all your work.

joe mclain

**Comment by jlaanstra** [comment]
Thanks again for helping to improve this library! It's appreciated. This bug is fixed in 7418d14a3f1b21bba0ae52818e67b616c4f9b34e

**Comment by jmclain** [comment]
Glad to help.
